services:
  - type: web
    name: randomalarm-backend
    runtime: python
    plan: free
    branch: main
    buildCommand: "pip install poetry && poetry install --no-dev"
    startCommand: "poetry run uvicorn app.main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
